// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OQS.CoreWebAPI.ResultsAndStatisticsModule.Database;

#nullable disable

namespace OQS.CoreWebAPI.Migrations
{
    [DbContext(typeof(RSMApplicationDbContext))]
    [Migration("20240421121839_RSMDbMigrate")]
    partial class RSMDbMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.QuestionResultBase", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("UserId", "QuestionId");

                    b.ToTable("QuestionResults");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QuestionResultBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuizResultBody", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "QuizId");

                    b.ToTable("QuizResultBodies");
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuizResultHeader", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionTime")
                        .HasColumnType("int");

                    b.Property<bool>("ReviewPending")
                        .HasColumnType("bit");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "QuizId");

                    b.ToTable("QuizResultHeaders");
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.ChoiceQuestionResult", b =>
                {
                    b.HasBaseType("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.QuestionResultBase");

                    b.Property<string>("PseudoDictionaryChoicesResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ChoiceQuestionResult");
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.ReviewNeededQuestionResult", b =>
                {
                    b.HasBaseType("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.QuestionResultBase");

                    b.Property<string>("ReviewNeededAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewNeededResult")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ReviewNeededQuestionResult");
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.TrueFalseQuestionResult", b =>
                {
                    b.HasBaseType("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.QuestionResultBase");

                    b.Property<int>("TrueFalseAnswerResult")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TrueFalseQuestionResult");
                });

            modelBuilder.Entity("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.WrittenAnswerQuestionResult", b =>
                {
                    b.HasBaseType("OQS.CoreWebAPI.ResultsAndStatisticsModule.Entities.QuestionResults.QuestionResultBase");

                    b.Property<string>("WrittenAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WrittenAnswerResult")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("WrittenAnswerQuestionResult");
                });
#pragma warning restore 612, 618
        }
    }
}
